// Shared deployment + seed logic (Phase 6 extract).
// Used by scripts/deploy.js, scripts/seed.js and scripts/demo-eval.js so the demo
// evaluator can deploy a deterministic stack in-process instead of duplicating
// the wiring order. Keep this file behaviour-identical to the Phase 1 scripts.
import fs from "fs";
import path from "path";

const ROOT = path.join(import.meta.dirname, "..", "..");
const CONFIG_PATH = path.join(ROOT, "frontend", "assets", "js", "contracts-config.js");

/// @notice Deploy Registry -> Inventory -> NFT -> Settlement -> Marketplace and wire them.
/// @param ethers Hardhat ethers instance from `network.create()`.
/// @return {Promise<{registry, inventory, nft, settlement, marketplace, addresses, deployer}>}
export async function deployStack(ethers) {
  const [deployer] = await ethers.getSigners();

  const Registry = await ethers.getContractFactory("AirlineRegistry");
  const registry = await Registry.deploy(deployer.address);
  await registry.waitForDeployment();

  const Inventory = await ethers.getContractFactory("FlightInventory");
  const inventory = await Inventory.deploy(await registry.getAddress(), deployer.address);
  await inventory.waitForDeployment();

  const NFT = await ethers.getContractFactory("AirTicketNFT");
  const nft = await NFT.deploy(
    await registry.getAddress(),
    await inventory.getAddress(),
    deployer.address
  );
  await nft.waitForDeployment();

  const Settlement = await ethers.getContractFactory("TicketSettlement");
  const settlement = await Settlement.deploy(
    await registry.getAddress(),
    await inventory.getAddress(),
    await nft.getAddress(),
    deployer.address
  );
  await settlement.waitForDeployment();

  const Marketplace = await ethers.getContractFactory("TicketMarketplace");
  const marketplace = await Marketplace.deploy(
    await registry.getAddress(),
    await inventory.getAddress(),
    await nft.getAddress(),
    deployer.address
  );
  await marketplace.waitForDeployment();

  // Wire authorized parties (reserve/release + mint/invalidate + controlled transfers).
  await (
    await inventory.setAuthorizedParties(
      await settlement.getAddress(),
      await marketplace.getAddress()
    )
  ).wait();
  await (await nft.setSettlement(await settlement.getAddress())).wait();
  const MARKETPLACE_ROLE = await nft.MARKETPLACE_ROLE();
  await (await nft.grantRole(MARKETPLACE_ROLE, await marketplace.getAddress())).wait();

  const addresses = {
    AirlineRegistry: await registry.getAddress(),
    FlightInventory: await inventory.getAddress(),
    AirTicketNFT: await nft.getAddress(),
    TicketSettlement: await settlement.getAddress(),
    TicketMarketplace: await marketplace.getAddress(),
  };

  return { registry, inventory, nft, settlement, marketplace, addresses, deployer: deployer.address };
}

/// @notice Write frontend/assets/js/contracts-config.js (chainId + addresses + ABIs, no secrets).
/// @param input { chainId, addresses } — chainId as number, addresses keyed by contract name.
export function writeFrontendConfig({ chainId, addresses }) {
  const abis = {};
  for (const name of Object.keys(addresses)) {
    const artifactPath = path.join(ROOT, "artifacts", "contracts", `${name}.sol`, `${name}.json`);
    abis[name] = JSON.parse(fs.readFileSync(artifactPath, "utf8")).abi;
  }

  const outDir = path.dirname(CONFIG_PATH);
  fs.mkdirSync(outDir, { recursive: true });
  const content =
    `// GENERATED by scripts/deploy.js - do not hand-edit.\n` +
    `window.CONTRACTS_CONFIG = ${JSON.stringify({ chainId, addresses, abis }, null, 2)};\n`;
  fs.writeFileSync(CONFIG_PATH, content);
  return { abiCount: Object.keys(abis).length, configPath: CONFIG_PATH };
}

/// @notice Parse the generated frontend config (addresses only; ABIs ignored here).
export function readFrontendConfig() {
  const raw = fs.readFileSync(CONFIG_PATH, "utf8");
  const json = raw.slice(raw.indexOf("{"), raw.lastIndexOf("}") + 1);
  return JSON.parse(json);
}

/// @notice Deterministic demo dataset (PRD §15 steps 1-2): approve one airline operator
///         wallet and publish one five-seat sample flight with the locked R1 policy values.
/// @param addresses Contract addresses from `deployStack`.
/// @return {Promise<{airline, admin, flightId, flightCode, departure}>}
export async function seedDemo(ethers, addresses) {
  const [admin, airline] = await ethers.getSigners();
  const registry = await ethers.getContractAt("AirlineRegistry", addresses.AirlineRegistry);
  const inventory = await ethers.getContractAt("FlightInventory", addresses.FlightInventory);

  if (!(await registry.isApproved(airline.address))) {
    await (await registry.connect(admin).approveAirline(airline.address)).wait();
  }

  const now = Math.floor(Date.now() / 1000);
  const departure = now + 30 * 24 * 3600;
  const refundDeadline = departure - 7 * 24 * 3600;
  const flightCode = "R1-DEMO-001";

  let flightId;
  const tx = await inventory.connect(airline).createFlight([
    flightCode,
    "JFK",
    "LHR",
    departure,
    5,
    ethers.parseEther("0.1"),
    refundDeadline,
    8000, // 80% refund
    500, // 5% royalty (<= maxRoyaltyBps 1000)
  ]);
  const receipt = await tx.wait();
  const created = receipt.logs
    .map((l) => {
      try {
        return inventory.interface.parseLog(l);
      } catch {
        return null;
      }
    })
    .find((e) => e && e.name === "FlightCreated");
  flightId = created.args.flightId.toString();
  await (await inventory.connect(airline).publishFlight(flightId)).wait();

  return {
    admin: admin.address,
    airline: airline.address,
    flightId,
    flightCode,
    departure,
    refundDeadline,
  };
}
