import fs from "fs";
import path from "path";
import { network } from "hardhat";

// Phase 1 deployment: Registry -> Inventory -> NFT -> Settlement -> Marketplace,
// then wire settlement/marketplace addresses and the NFT marketplace role.
// Writes frontend/assets/js/contracts-config.js (chainId + addresses, no secrets).
async function main() {
  const { ethers } = await network.create();
  const [deployer] = await ethers.getSigners();
  const net = await ethers.provider.getNetwork();

  const Registry = await ethers.getContractFactory("AirlineRegistry");
  const registry = await Registry.deploy(deployer.address);
  await registry.waitForDeployment();

  const Inventory = await ethers.getContractFactory("FlightInventory");
  const inventory = await Inventory.deploy(
    await registry.getAddress(),
    deployer.address
  );
  await inventory.waitForDeployment();

  const NFT = await ethers.getContractFactory("AirTicketNFT");
  const nft = await NFT.deploy(
    await registry.getAddress(),
    await inventory.getAddress(),
    deployer.address
  );
  await nft.waitForDeployment();

  const Settlement = await ethers.getContractFactory("TicketSettlement");
  const settlement = await Settlement.deploy(
    await registry.getAddress(),
    await inventory.getAddress(),
    await nft.getAddress(),
    deployer.address
  );
  await settlement.waitForDeployment();

  const Marketplace = await ethers.getContractFactory("TicketMarketplace");
  const marketplace = await Marketplace.deploy(
    await registry.getAddress(),
    await inventory.getAddress(),
    await nft.getAddress(),
    deployer.address
  );
  await marketplace.waitForDeployment();

  // Wire authorized parties (reserve/release + mint/invalidate + controlled transfers).
  await (await inventory.setAuthorizedParties(
    await settlement.getAddress(),
    await marketplace.getAddress()
  )).wait();
  await (await nft.setSettlement(await settlement.getAddress())).wait();
  const MARKETPLACE_ROLE = await nft.MARKETPLACE_ROLE();
  await (await nft.grantRole(MARKETPLACE_ROLE, await marketplace.getAddress())).wait();

  const addresses = {
    AirlineRegistry: await registry.getAddress(),
    FlightInventory: await inventory.getAddress(),
    AirTicketNFT: await nft.getAddress(),
    TicketSettlement: await settlement.getAddress(),
    TicketMarketplace: await marketplace.getAddress(),
  };
  const chainId = Number(net.chainId);

  const outDir = path.join(import.meta.dirname, "..", "frontend", "assets", "js");
  fs.mkdirSync(outDir, { recursive: true });
  const content =
    `// GENERATED by scripts/deploy.js — do not hand-edit.\n` +
    `window.CONTRACTS_CONFIG = ${JSON.stringify({ chainId, addresses }, null, 2)};\n`;
  fs.writeFileSync(path.join(outDir, "contracts-config.js"), content);

  console.log(JSON.stringify({ chainId, deployer: deployer.address, addresses }, null, 2));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
